### ISSUE TITLE
KPT 회고 220321 2주차 월요일

### ISSUE THREAD

**Issue by sun-one95** [codestates/cocodus#110]
#### 작성자
- 권순일 / 프론트엔드 / sun-one95

#### 1. Keep (유지할 항목)
- Team Rule
  - 의사 소통을 서로 잘 지켜 나가고 있음
  - 팀 규칙을 잘 이행하고 있음

#### 2. Problem (문제라고 생각하는 항목)
- SR 피드백
  - 와이어프레임, DB 다이어그램, API 문서, Tech Reference 항목이 수정을 필요로 함
 
#### 3. Try (Action Items)
- [ ] 피드백 받은 내용을 바탕으로 SR 수정
- [ ] 기능 구현

**Comment by rmfhsep** [comment]
SR 피드백에 따른 기획 수정이 어느정도 필요할텐데, 프로젝트 작업에 무리가 가지 않는 선에서 잘 진행해 주세요!
작업 진행중에도 수정이 필요할 경우가 많이 생길것입니다.
시간 분배 잘하여 태스크 처리에 무리 없게 해 주세요!
건강 유의하시면서 화이팅입니다!👍
