### ISSUE TITLE
KPT 회고 220328 3주차 월요일

### ISSUE THREAD

**Issue by ToyCon** [codestates/cocodus#148]
#### 작성자
- 김현덕 / 백엔드 / ToyCon

#### 1. Keep (유지할 항목)
- 프로젝트 진행 속도가 나쁘지 않음
  - 다만 위치 관련 기능 구현을 이번주부터 꼭 시작해야 함
- 룰 잘 지켜지고 있음
  - 의사소통 규칙 잘 지키고 있음
  - 체력 관리도 이상 없음
#### 2. Problem (문제라고 생각하는 항목)
- 위치 불러오기 기능을 전혀 신경쓰지 못하고 있음
  - 프론트에서 카카오맵 적용 구현
  - 백엔드에서 클라이언트가 제공한 위치를 바탕으로 가까운 거리 정렬하는 로직 구현
#### 3. Try (Action Items)
- [x] 위치 관련 기능을 프론트 1명, 백엔드 1명이 공부해서 구현
- [x] 같은 파트 팀원이 Task 도와주기
- [x] 프론트엔드 민주님
- [x] 백엔드 종복님

**Comment by rmfhsep** [comment]
프로젝트의 3주차가 시작되었네요.
진행 속도에 대해 나쁘지 않다고 해 주시니 정말 좋은 상황이군요!
거리를 계산하는데에는 카카오맵과 geolocation api를 사용하신다면 도움이 되실거예요!
무엇보다 건강을 우선시하며 프로젝트 진행 부탁드립니다.
화이팅하세요!👍
