### ISSUE TITLE
KPT 회고 220404 4주차 월요일

### ISSUE THREAD

**Issue by ToyCon** [codestates/cocodus#191]
#### 작성자
- 김현덕 / 백엔드 / ToyCon

#### 1. Keep (유지할 항목)
- 공동작업이 많은데 협업이 정상적으로 잘 진행되고 있음
  - 팀 룰에서 정한 의사소통 규칙을 잘 지키고 있음
- 건강 관리
  - 3주차까지 작업에 속도를 내서 4주차는 여유를 가지고 작업중
  - 무리하지 않고 반드시 필요한 부분부터 체크해서 진행 중
- 프로젝트 작업 속도 유지
  - 프로젝트 핵심 기능을 포함 대부분의 기능을 클라이언트에서 구현
  - 서버 및 연동은 작업중
  - 자동배포 및 파이프라인 구축은 1주차에 완료(happy5happy5)

#### 2. Problem (문제라고 생각하는 항목)
- 모임 정보를 위치 기반으로 분류하는 로직 작업이 필요
  - 구체적으로 어떤 방식으로 구현할지에 대한 고민을 하지 못했음
  - 코플릿 문제 및 카카오맵 API 검색으로 현재 구현 방식 고민중

#### 3. Try (Action Items)
- [ ] 스몰톡 진행 및 테스트 전 최종 점검
- [ ] 내 위치를 중심으로 모임 정보를 정렬하는 로직 구현
- [ ] 클라이언트 - 서버 연동 작업 마무리
- [ ] 최종 배포 테스트
- [ ] 여유 시간이 된다면 코드 리팩토링

**Comment by rmfhsep** [comment]
프로젝트의 마지막 주간입니다.
현재는 아쉬운 부분이 있더라도, 테스트를 진행해 보시고
지금까지 한 작업들을 보완하는 작업이 필요합니다.
마지막까지 팀원들과 합심하여 화이팅입니다!
