### ISSUE TITLE
개발환경 통합 설정

### ISSUE THREAD

**Issue by Minju20200305** [codestates/cocodus#20]
ISSUE
Group: sr
Type: SR
Detail: fix actions from client redux
TODO
- [x] 개발환경 통합설정
Estimated time
Pick one
2h

Labels
Estimated time: E: 2h
Group: client, server
Sprint: Sprint__1
Urgency: Middle

**Comment by ToyCon** [comment]
클라이언트 / 서버 모두 불필요한 패키지 정보 삭제, 서버 쪽 JWT 라이브러리 추가하여 main 브랜치에 반영 완료
