### ISSUE TITLE
브랜치 설정

### ISSUE THREAD

**Issue by Minju20200305** [codestates/cocodus#55]
ISSUE
Group: client, server
Type:  feature
Detail: 브랜치 설정
TODO
 - [x] 브랜치 설정
Estimated time
1h

Labels
Estimated time: E: 1h
Group : client, server
Sprint: Sprint__2__
Urgency: Middle

**Comment by ToyCon** [comment]
Dev 브랜치에 PR, main은 팀장만 보고 판단하여 머지
