### ISSUE TITLE
RDS 생성 및 EC2와 연결

### ISSUE THREAD

**Issue by Minju20200305** [codestates/cocodus#62]
ISSUE
Group: server
Type: feature
Detail: RDS 생성 및 EC2와 연결
TODO
- [x] RDS 생성 
- [x] EC2와 연결
Estimated time
3h
Labels
Estimated time: E: 3h
Group: server
Sprint: Sprint__2__
Urgency: High

**Comment by ToyCon** [comment]
AWS EC2:  happy5happy5
AWS RDS: ToyCon
