### ISSUE TITLE
도메인 구입 및 연결 

### ISSUE THREAD

**Issue by Minju20200305** [codestates/cocodus#64]
ISSUE
Group: server
Type: 
Detail: 도메인 구입 및 연결 
TODO
- [x] 도메인 구입
- [x] 도메인 연결 
Estimated time
3h

Labels
Estimated time: E: 3h
Group : server
Sprint: Sprint__2__
Urgency: Middle

**Comment by ToyCon** [comment]
도메인 구입 + Cloudfront 설정 후 HTTPS 배포까지 완료
