### ISSUE TITLE
RDS에 데이터베이스 및 테이블 생성

### ISSUE THREAD

**Issue by Minju20200305** [codestates/cocodus#67]
ISSUE
Group: server
Type: feature
Detail: RDS에 데이터베이스 및 테이블 생성
TODO
- [x] RDS에 데이터베이스 
- [x] 테이블 생성
Estimated time
2h

Labels
Estimated time: E: 2h
Group: server
Sprint: Sprint__2__
Urgency: Middle

**Comment by ToyCon** [comment]
RDS 접속, sequelize로 마이그레이션 작동 모두 확인
