### ISSUE TITLE
KPT 회고 220317 1주차 금요일

### ISSUE THREAD

**Issue by ToyCon** [codestates/cocodus#98]
#### 작성자
- 김현덕(팀장) / 백엔드 / ToyCon

#### 1. Keep (유지할 항목)
- 의사소통이 잘 되고 있음
  - 의견 대립이 있었으나, 근거를 모두 들어보고 프로젝트 진행에 더 적합하다고 생각하는 의견을 선택하는 방식으로 대립을 해결하였음
  - 의사소통과 관련된 항목을 팀 규칙에 자세하게 정함
  - 규칙을 팀원 모두 잘 지키고 있어 의사소통은 앞으로도 큰 문제가 없다고 예상함
- 프로젝트에 사용할 시간과 휴식을 취할 시간을 명확하게 분리
  - 총 4주, 남은 시간도 앞으로 3주 이상이어서 컨디션 관리가 분명히 필요하다고 판단했음
  - 컨디션 관리에 어려움을 겪는 인원이 많아서 '모니터를 주시하지 않는' '휴식시간'을 1시간 이상 가지도록 팀 규칙에 명문화
#### 2. Problem (문제라고 생각하는 항목)
- SR 진행에 시간을 많이 소비함
  - 첫날 아이디어 선정은 빠르게 진행하였음
  - 프론트엔드와 백엔드가 같이 진행해야 하는 단계에서 시간을 많이 소비하였음
  - 프로젝트가 한참 진행 됐을 때 업무의 양이 어느정도인지를 고려해서 시간 사용에 한계를 정해야 했는데 그렇게 하지 못함. 이 부분은 팀장으로서 잘못 판단했다고 생각
- SR을 진행하면서 초기 배포 환경을 구축하려고 했으나 실패
  - AWS EC2/S3 생성을 통해 테스트 배포를 먼저 진행한 뒤 API 문서를 작성하고자 하였으나 EC2 생성 후 express 설치 or 구동 과정에서 진행이 불가하여 API 문서 작업이 연기됨
#### 3. Try (Action Items)
- [ ] 코드 리뷰 시간을 유의미하게 활용할 수 있는 방안을 찾아야 함
- [ ] EC2 생성 및 서버 구동을 최우선적으로 해결(백엔드)

**Comment by rmfhsep** [comment]
파이널 프로젝트의 시작을 응원합니다!🙌
커뮤니케이션을 굉장히 잘 해주고 계시네요!
기획에 약간의 이슈가생기는 것은 어쩌면 당연하다고 생각합니다. 
누구 한 명의 잘못이 아니예요! 모두가 처음이니 모르는 것이 많은것은 당연합니다.
프로젝트 진행 중 많은 성장을 하실 수 있을 거예요
화이팅하세요!👍
